import type { Bitrix24ApiClient } from "../../api-client.js";
import type { ToolDefinition } from "../../types.js";
import { createActionTool } from "../framework.js";
import { P } from "../params.js";
import { API_VERSION } from "../../constants.js";

export function createActivitiesTool(client: Bitrix24ApiClient): ToolDefinition {
  return createActionTool(
    "bx24_crm_activities",
    `Bitrix24 CRM activities (дела/звонки/встречи/письма): CRUD, complete, todo, configurable, types, badges, timeline (comments/notes/logmessages/bindings). Methods crm.activity.*, crm.activity.todo.*, crm.activity.configurable.*, crm.activity.type.*, crm.activity.badge.*, crm.timeline.* (${API_VERSION}). RU/EN: дело, запланируй звонок, запланируй встречу, заверши дело, таймлайн, заметка, лог / activity, plan a call, plan a meeting, complete activity, timeline, note, log.`,
    [
      "add", "get", "list", "update", "delete", "fields", "complete", "count",
      "binding_add", "binding_delete", "binding_list", "binding_fields",
      "todo_add", "todo_get", "todo_list", "todo_update", "todo_delete", "todo_fields",
      "configurable_add", "configurable_get", "configurable_list", "configurable_update", "configurable_delete", "configurable_fields",
      "type_add", "type_get", "type_list", "type_update", "type_delete", "type_fields",
      "badge_add", "badge_get", "badge_list", "badge_update", "badge_delete", "badge_fields",
      "timeline_comment_add", "timeline_comment_update", "timeline_comment_get", "timeline_comment_list", "timeline_comment_delete", "timeline_comment_fields",
      "timeline_list", "timeline_note_save", "timeline_note_get", "timeline_note_delete",
      "timeline_bindings_bind", "timeline_bindings_list", "timeline_bindings_unbind", "timeline_bindings_fields",
      "timeline_logmessage_add", "timeline_logmessage_get", "timeline_logmessage_list", "timeline_logmessage_delete",
      "timeline_item_pin", "timeline_item_unpin",
    ],
    {
      id: P.id, fields: { type: "object", description: "Activity fields: TYPE_ID, SUBJECT, DESCRIPTION, START_TIME, END_TIME, COMPLETED, OWNER_ID, OWNER_TYPE_ID, RESPONSIBLE_ID." },
      filter: P.filter, select: P.select, order: P.order, start: P.start,
      ownerId: P.ownerId, ownerTypeId: { type: "string", description: "Owner type: 1=lead,2=deal,3=contact,4=company" },
      comment: { type: "string", description: "Timeline comment/log/note text" },
      commentId: { type: "string", description: "Timeline comment ID" },
    },
    {
      add: { restMethod: "crm.activity.add", httpVerb: "POST", bodyParam: "fields", bodyWrapper: "fields" },
      get: { restMethod: "crm.activity.get", httpVerb: "GET", pathParams: ["id"] },
      list: { restMethod: "crm.activity.list", httpVerb: "GET", isList: true, queryParams: ["filter", "select", "order", "start"] },
      update: { restMethod: "crm.activity.update", httpVerb: "POST", pathParams: ["id"], bodyParam: "fields", bodyWrapper: "fields" },
      delete: { restMethod: "crm.activity.delete", httpVerb: "POST", pathParams: ["id"] },
      fields: { restMethod: "crm.activity.fields", httpVerb: "GET" },
      complete: { restMethod: "crm.activity.complete", httpVerb: "POST", pathParams: ["id"] },
      count: { restMethod: "crm.activity.list", httpVerb: "GET", queryParams: ["filter", "select"] },
      binding_add: { restMethod: "crm.activity.binding.add", httpVerb: "POST", pathParams: ["id"], bodyParam: "ownerId", bodyWrapper: "fields" },
      binding_delete: { restMethod: "crm.activity.binding.delete", httpVerb: "POST", pathParams: ["id", "ownerId"] },
      binding_list: { restMethod: "crm.activity.binding.list", httpVerb: "GET", pathParams: ["id"] },
      binding_fields: { restMethod: "crm.activity.binding.fields", httpVerb: "GET" },
      todo_add: { restMethod: "crm.activity.todo.add", httpVerb: "POST", bodyParam: "fields", bodyWrapper: "fields" },
      todo_get: { restMethod: "crm.activity.todo.get", httpVerb: "GET", pathParams: ["id"] },
      todo_list: { restMethod: "crm.activity.todo.list", httpVerb: "GET", isList: true, queryParams: ["filter", "select", "order", "start"] },
      todo_update: { restMethod: "crm.activity.todo.update", httpVerb: "POST", pathParams: ["id"], bodyParam: "fields", bodyWrapper: "fields" },
      todo_delete: { restMethod: "crm.activity.todo.delete", httpVerb: "POST", pathParams: ["id"] },
      todo_fields: { restMethod: "crm.activity.todo.fields", httpVerb: "GET" },
      configurable_add: { restMethod: "crm.activity.configurable.add", httpVerb: "POST", bodyParam: "fields", bodyWrapper: "fields" },
      configurable_get: { restMethod: "crm.activity.configurable.get", httpVerb: "GET", pathParams: ["id"] },
      configurable_list: { restMethod: "crm.activity.configurable.list", httpVerb: "GET", isList: true, queryParams: ["filter", "select", "order", "start"] },
      configurable_update: { restMethod: "crm.activity.configurable.update", httpVerb: "POST", pathParams: ["id"], bodyParam: "fields", bodyWrapper: "fields" },
      configurable_delete: { restMethod: "crm.activity.configurable.delete", httpVerb: "POST", pathParams: ["id"] },
      configurable_fields: { restMethod: "crm.activity.configurable.fields", httpVerb: "GET" },
      type_add: { restMethod: "crm.activity.type.add", httpVerb: "POST", bodyParam: "fields", bodyWrapper: "fields" },
      type_get: { restMethod: "crm.activity.type.get", httpVerb: "GET", pathParams: ["id"] },
      type_list: { restMethod: "crm.activity.type.list", httpVerb: "GET", isList: true, queryParams: ["filter", "select", "order", "start"] },
      type_update: { restMethod: "crm.activity.type.update", httpVerb: "POST", pathParams: ["id"], bodyParam: "fields", bodyWrapper: "fields" },
      type_delete: { restMethod: "crm.activity.type.delete", httpVerb: "POST", pathParams: ["id"] },
      type_fields: { restMethod: "crm.activity.type.fields", httpVerb: "GET" },
      badge_add: { restMethod: "crm.activity.badge.add", httpVerb: "POST", bodyParam: "fields", bodyWrapper: "fields" },
      badge_get: { restMethod: "crm.activity.badge.get", httpVerb: "GET", pathParams: ["id"] },
      badge_list: { restMethod: "crm.activity.badge.list", httpVerb: "GET", isList: true, queryParams: ["filter", "select", "order", "start"] },
      badge_update: { restMethod: "crm.activity.badge.update", httpVerb: "POST", pathParams: ["id"], bodyParam: "fields", bodyWrapper: "fields" },
      badge_delete: { restMethod: "crm.activity.badge.delete", httpVerb: "POST", pathParams: ["id"] },
      badge_fields: { restMethod: "crm.activity.badge.fields", httpVerb: "GET" },
      timeline_comment_add: { restMethod: "crm.timeline.comment.add", httpVerb: "POST", pathParams: ["ownerId"], bodyParam: "comment", bodyWrapper: "fields" },
      timeline_comment_update: { restMethod: "crm.timeline.comment.update", httpVerb: "POST", pathParams: ["commentId"], bodyParam: "fields", bodyWrapper: "fields" },
      timeline_comment_get: { restMethod: "crm.timeline.comment.get", httpVerb: "GET", pathParams: ["commentId"] },
      timeline_comment_list: { restMethod: "crm.timeline.comment.list", httpVerb: "GET", isList: true, queryParams: ["filter", "select", "order", "start"] },
      timeline_comment_delete: { restMethod: "crm.timeline.comment.delete", httpVerb: "POST", pathParams: ["commentId"] },
      timeline_comment_fields: { restMethod: "crm.timeline.comment.fields", httpVerb: "GET" },
      timeline_list: { restMethod: "crm.timeline.item.list", httpVerb: "GET", isList: true, queryParams: ["filter", "select", "order"] },
      timeline_note_save: { restMethod: "crm.timeline.note.save", httpVerb: "POST", bodyParam: "fields", bodyWrapper: "fields" },
      timeline_note_get: { restMethod: "crm.timeline.note.get", httpVerb: "GET", pathParams: ["id"] },
      timeline_note_delete: { restMethod: "crm.timeline.note.delete", httpVerb: "POST", pathParams: ["id"] },
      timeline_bindings_bind: { restMethod: "crm.timeline.bindings.bind", httpVerb: "POST", bodyParam: "fields", bodyWrapper: "fields" },
      timeline_bindings_list: { restMethod: "crm.timeline.bindings.list", httpVerb: "GET", isList: true, queryParams: ["filter", "select", "order", "start"] },
      timeline_bindings_unbind: { restMethod: "crm.timeline.bindings.unbind", httpVerb: "POST", bodyParam: "fields", bodyWrapper: "fields" },
      timeline_bindings_fields: { restMethod: "crm.timeline.bindings.fields", httpVerb: "GET" },
      timeline_logmessage_add: { restMethod: "crm.timeline.logmessage.add", httpVerb: "POST", pathParams: ["ownerId"], bodyParam: "comment", bodyWrapper: "fields" },
      timeline_logmessage_get: { restMethod: "crm.timeline.logmessage.get", httpVerb: "GET", pathParams: ["id"] },
      timeline_logmessage_list: { restMethod: "crm.timeline.logmessage.list", httpVerb: "GET", isList: true, queryParams: ["filter", "select", "order", "start"] },
      timeline_logmessage_delete: { restMethod: "crm.timeline.logmessage.delete", httpVerb: "POST", pathParams: ["id"] },
      timeline_item_pin: { restMethod: "crm.timeline.item.pin", httpVerb: "POST", pathParams: ["id"] },
      timeline_item_unpin: { restMethod: "crm.timeline.item.unpin", httpVerb: "POST", pathParams: ["id"] },
    },
    client,
    {
      add: "Create an activity (call/meeting/task). Bind with OWNER_ID + OWNER_TYPE_ID.",
      get: "Get an activity by ID", list: "List/filter activities", update: "Update an activity",
      delete: "Delete an activity (destructive)", fields: "Describe activity fields",
      complete: "Mark an activity completed", count: "Count activities by filter",
      binding_add: "Bind an activity to an entity", binding_delete: "Remove a binding (destructive)",
      binding_list: "List activity bindings", binding_fields: "Describe binding fields",
      todo_add: "Add a todo activity", todo_get: "Get a todo activity", todo_list: "List todo activities",
      todo_update: "Update a todo activity", todo_delete: "Delete a todo activity (destructive)", todo_fields: "Describe todo fields",
      configurable_add: "Add a configurable activity", configurable_get: "Get a configurable activity",
      configurable_list: "List configurable activities", configurable_update: "Update a configurable activity",
      configurable_delete: "Delete a configurable activity (destructive)", configurable_fields: "Describe configurable activity fields",
      type_add: "Add an activity type", type_get: "Get an activity type", type_list: "List activity types",
      type_update: "Update an activity type", type_delete: "Delete an activity type (destructive)", type_fields: "Describe type fields",
      badge_add: "Add an activity badge", badge_get: "Get an activity badge", badge_list: "List activity badges",
      badge_update: "Update an activity badge", badge_delete: "Delete an activity badge (destructive)", badge_fields: "Describe badge fields",
      timeline_comment_add: "Add a timeline comment to an entity", timeline_comment_update: "Update a timeline comment",
      timeline_comment_get: "Get a timeline comment", timeline_comment_list: "List timeline comments",
      timeline_comment_delete: "Delete a timeline comment (destructive)", timeline_comment_fields: "Describe comment fields",
      timeline_list: "List timeline items", timeline_note_save: "Save a timeline note",
      timeline_note_get: "Get a timeline note", timeline_note_delete: "Delete a timeline note (destructive)",
      timeline_bindings_bind: "Bind a timeline record to entities", timeline_bindings_list: "List timeline bindings",
      timeline_bindings_unbind: "Unbind a timeline record (destructive)", timeline_bindings_fields: "Describe binding fields",
      timeline_logmessage_add: "Add a timeline log message", timeline_logmessage_get: "Get a log message",
      timeline_logmessage_list: "List log messages", timeline_logmessage_delete: "Delete a log message (destructive)",
      timeline_item_pin: "Pin a timeline record", timeline_item_unpin: "Unpin a timeline record",
    },
  );
}