import type { Bitrix24ApiClient } from "../../api-client.js";
import type { ToolDefinition } from "../../types.js";
import { createActionTool } from "../framework.js";
import { P } from "../params.js";
import { API_VERSION } from "../../constants.js";

export function createProductsTool(client: Bitrix24ApiClient): ToolDefinition {
  return createActionTool(
    "bx24_crm_products",
    `Bitrix24 trade catalog: products, sections, prices, stores, product rows, price types, measures, VAT, ratios, rounding rules, extra charges, inventory documents, product properties, variations (offers), SKU heads, services. Methods catalog.* (${API_VERSION}). RU/EN: каталог, товар, раздел, цена, склад, товарная позиция, вариация, услуга, тип цены, единица измерения, НДС, коэффициент, документ склада, свойство товара / catalog, product, section, price, store, variation, offer, sku, service, price type, measure, VAT, ratio, inventory document, product property.`,
    [
      // base product / section / price / store / productrow (existing)
      "product_add", "product_get", "product_list", "product_update", "product_delete", "product_fields",
      "section_add", "section_get", "section_list", "section_update", "section_delete", "section_fields",
      "price_add", "price_get", "price_list", "price_update", "price_delete", "price_fields",
      "store_add", "store_get", "store_list", "store_update", "store_delete", "store_fields",
      "productrow_add", "productrow_get", "productrow_list",
      // catalog metadata
      "catalog_list", "catalog_get", "catalog_isOffers", "catalog_fields",
      // price types
      "priceType_add", "priceType_get", "priceType_list", "priceType_update", "priceType_delete", "priceType_fields",
      // measures (units)
      "measure_add", "measure_get", "measure_list", "measure_update", "measure_delete", "measure_fields",
      // VAT
      "vat_add", "vat_get", "vat_list", "vat_update", "vat_delete", "vat_fields",
      // ratios
      "ratio_list", "ratio_fields",
      // rounding rules
      "roundingRule_add", "roundingRule_get", "roundingRule_list", "roundingRule_update", "roundingRule_delete", "roundingRule_fields",
      // extra charges
      "extra_get", "extra_list", "extra_fields",
      // stock records (storeProduct)
      "storeProduct_get", "storeProduct_list", "storeProduct_fields",
      // inventory documents
      "document_add", "document_list", "document_update", "document_delete", "document_conduct", "document_cancel", "document_modeStatus", "document_fields",
      "document_element_add", "document_element_list", "document_element_update", "document_element_delete", "document_element_fields",
      "documentcontractor_add", "documentcontractor_list", "documentcontractor_delete", "documentcontractor_fields",
      // product properties + enum + feature + section binding
      "property_add", "property_get", "property_list", "property_update", "property_delete", "property_fields",
      "propertyEnum_add", "propertyEnum_get", "propertyEnum_list", "propertyEnum_update", "propertyEnum_delete", "propertyEnum_fields",
      "propertyFeature_add", "propertyFeature_get", "propertyFeature_list", "propertyFeature_update", "propertyFeature_availableFeatures", "propertyFeature_fields",
      "propertySection_set", "propertySection_get", "propertySection_list",
      // product kinds: offers (variations) / sku heads / services
      "offer_add", "offer_get", "offer_list", "offer_update", "offer_delete", "offer_fields",
      "sku_add", "sku_get", "sku_list", "sku_update", "sku_delete", "sku_fields",
      "service_add", "service_get", "service_list", "service_update", "service_delete", "service_fields",
      // enums
      "enum_getRoundTypes", "enum_getStoreDocumentTypes",
    ],
    {
      id: P.id, fields: { type: "object", description: "Product/section/price/etc. fields (per Bitrix24 docs for the method)" },
      filter: P.filter, select: P.select, order: P.order, start: P.start,
      sectionFields: { type: "object", description: "Section fields: NAME, IBLOCK_ID" },
      priceFields: { type: "object", description: "Price: {PRODUCT_ID, PRICE, CURRENCY, PRICE_TYPE_ID}" },
      rowFields: { type: "object", description: "Product row: {PRODUCT_ID, PRICE, QUANTITY, OWNER_TYPE, OWNER_ID}" },
      // extended IDs
      catalogId: P.catalogId, priceTypeId: P.priceTypeId, measureId: P.measureId, vatId: P.vatId,
      storeProductId: P.storeProductId, ratioId: P.ratioId, roundingRuleId: P.roundingRuleId, extraId: P.extraId,
      inventoryDocumentId: P.inventoryDocumentId, contractorId: P.contractorId,
      propertyId: P.propertyId, propertyEnumId: P.propertyEnumId, featureId: P.featureId,
    },
    {
      // base
      product_add: { restMethod: "catalog.product.add", httpVerb: "POST", bodyParam: "fields", bodyWrapper: "fields" },
      product_get: { restMethod: "catalog.product.get", httpVerb: "GET", pathParams: ["id"] },
      product_list: { restMethod: "catalog.product.list", httpVerb: "GET", isList: true, queryParams: ["filter", "select", "order", "start"] },
      product_update: { restMethod: "catalog.product.update", httpVerb: "POST", pathParams: ["id"], bodyParam: "fields", bodyWrapper: "fields" },
      product_delete: { restMethod: "catalog.product.delete", httpVerb: "POST", pathParams: ["id"] },
      product_fields: { restMethod: "catalog.product.fields", httpVerb: "GET" },
      section_add: { restMethod: "catalog.section.add", httpVerb: "POST", bodyParam: "sectionFields", bodyWrapper: "fields" },
      section_get: { restMethod: "catalog.section.get", httpVerb: "GET", pathParams: ["id"] },
      section_list: { restMethod: "catalog.section.list", httpVerb: "GET", isList: true, queryParams: ["filter", "select", "order", "start"] },
      section_update: { restMethod: "catalog.section.update", httpVerb: "POST", pathParams: ["id"], bodyParam: "sectionFields", bodyWrapper: "fields" },
      section_delete: { restMethod: "catalog.section.delete", httpVerb: "POST", pathParams: ["id"] },
      section_fields: { restMethod: "catalog.section.getFields", httpVerb: "GET" },
      price_add: { restMethod: "catalog.price.add", httpVerb: "POST", bodyParam: "priceFields", bodyWrapper: "fields" },
      price_get: { restMethod: "catalog.price.get", httpVerb: "GET", pathParams: ["id"] },
      price_list: { restMethod: "catalog.price.list", httpVerb: "GET", isList: true, queryParams: ["filter", "select", "order", "start"] },
      price_update: { restMethod: "catalog.price.update", httpVerb: "POST", pathParams: ["id"], bodyParam: "priceFields", bodyWrapper: "fields" },
      price_delete: { restMethod: "catalog.price.delete", httpVerb: "POST", pathParams: ["id"] },
      price_fields: { restMethod: "catalog.price.getFields", httpVerb: "GET" },
      store_add: { restMethod: "catalog.store.add", httpVerb: "POST", bodyParam: "fields", bodyWrapper: "fields" },
      store_get: { restMethod: "catalog.store.get", httpVerb: "GET", pathParams: ["id"] },
      store_list: { restMethod: "catalog.store.list", httpVerb: "GET", isList: true, queryParams: ["filter", "select", "order", "start"] },
      store_update: { restMethod: "catalog.store.update", httpVerb: "POST", pathParams: ["id"], bodyParam: "fields", bodyWrapper: "fields" },
      store_delete: { restMethod: "catalog.store.delete", httpVerb: "POST", pathParams: ["id"] },
      store_fields: { restMethod: "catalog.store.getFields", httpVerb: "GET" },
      productrow_add: { restMethod: "crm.item.productrow.add", httpVerb: "POST", bodyParam: "rowFields", bodyWrapper: "fields" },
      productrow_get: { restMethod: "crm.item.productrow.get", httpVerb: "GET", pathParams: ["id"] },
      productrow_list: { restMethod: "crm.item.productrow.list", httpVerb: "GET", isList: true, queryParams: ["filter", "select", "order", "start"] },
      // catalog metadata
      catalog_list: { restMethod: "catalog.catalog.list", httpVerb: "GET", isList: true, queryParams: ["filter", "select", "order", "start"] },
      catalog_get: { restMethod: "catalog.catalog.get", httpVerb: "GET", pathParams: ["catalogId"] },
      catalog_isOffers: { restMethod: "catalog.catalog.isOffers", httpVerb: "GET", pathParams: ["catalogId"] },
      catalog_fields: { restMethod: "catalog.catalog.getFields", httpVerb: "GET" },
      // price types
      priceType_add: { restMethod: "catalog.priceType.add", httpVerb: "POST", bodyParam: "fields", bodyWrapper: "fields" },
      priceType_get: { restMethod: "catalog.priceType.get", httpVerb: "GET", pathParams: ["priceTypeId"] },
      priceType_list: { restMethod: "catalog.priceType.list", httpVerb: "GET", isList: true, queryParams: ["filter", "select", "order", "start"] },
      priceType_update: { restMethod: "catalog.priceType.update", httpVerb: "POST", pathParams: ["priceTypeId"], bodyParam: "fields", bodyWrapper: "fields" },
      priceType_delete: { restMethod: "catalog.priceType.delete", httpVerb: "POST", pathParams: ["priceTypeId"] },
      priceType_fields: { restMethod: "catalog.priceType.getFields", httpVerb: "GET" },
      // measures
      measure_add: { restMethod: "catalog.measure.add", httpVerb: "POST", bodyParam: "fields", bodyWrapper: "fields" },
      measure_get: { restMethod: "catalog.measure.get", httpVerb: "GET", pathParams: ["measureId"] },
      measure_list: { restMethod: "catalog.measure.list", httpVerb: "GET", isList: true, queryParams: ["filter", "select", "order", "start"] },
      measure_update: { restMethod: "catalog.measure.update", httpVerb: "POST", pathParams: ["measureId"], bodyParam: "fields", bodyWrapper: "fields" },
      measure_delete: { restMethod: "catalog.measure.delete", httpVerb: "POST", pathParams: ["measureId"] },
      measure_fields: { restMethod: "catalog.measure.getFields", httpVerb: "GET" },
      // VAT
      vat_add: { restMethod: "catalog.vat.add", httpVerb: "POST", bodyParam: "fields", bodyWrapper: "fields" },
      vat_get: { restMethod: "catalog.vat.get", httpVerb: "GET", pathParams: ["vatId"] },
      vat_list: { restMethod: "catalog.vat.list", httpVerb: "GET", isList: true, queryParams: ["filter", "select", "order", "start"] },
      vat_update: { restMethod: "catalog.vat.update", httpVerb: "POST", pathParams: ["vatId"], bodyParam: "fields", bodyWrapper: "fields" },
      vat_delete: { restMethod: "catalog.vat.delete", httpVerb: "POST", pathParams: ["vatId"] },
      vat_fields: { restMethod: "catalog.vat.getFields", httpVerb: "GET" },
      // ratios
      ratio_list: { restMethod: "catalog.ratio.list", httpVerb: "GET", isList: true, queryParams: ["filter", "select", "order", "start"] },
      ratio_fields: { restMethod: "catalog.ratio.getFields", httpVerb: "GET" },
      // rounding rules
      roundingRule_add: { restMethod: "catalog.roundingRule.add", httpVerb: "POST", bodyParam: "fields", bodyWrapper: "fields" },
      roundingRule_get: { restMethod: "catalog.roundingRule.get", httpVerb: "GET", pathParams: ["roundingRuleId"] },
      roundingRule_list: { restMethod: "catalog.roundingRule.list", httpVerb: "GET", isList: true, queryParams: ["filter", "select", "order", "start"] },
      roundingRule_update: { restMethod: "catalog.roundingRule.update", httpVerb: "POST", pathParams: ["roundingRuleId"], bodyParam: "fields", bodyWrapper: "fields" },
      roundingRule_delete: { restMethod: "catalog.roundingRule.delete", httpVerb: "POST", pathParams: ["roundingRuleId"] },
      roundingRule_fields: { restMethod: "catalog.roundingRule.getFields", httpVerb: "GET" },
      // extra charges
      extra_get: { restMethod: "catalog.extra.get", httpVerb: "GET", pathParams: ["extraId"] },
      extra_list: { restMethod: "catalog.extra.list", httpVerb: "GET", isList: true, queryParams: ["filter", "select", "order", "start"] },
      extra_fields: { restMethod: "catalog.extra.getFields", httpVerb: "GET" },
      // stock records
      storeProduct_get: { restMethod: "catalog.storeproduct.get", httpVerb: "GET", pathParams: ["storeProductId"] },
      storeProduct_list: { restMethod: "catalog.storeproduct.list", httpVerb: "GET", isList: true, queryParams: ["filter", "select", "order", "start"] },
      storeProduct_fields: { restMethod: "catalog.storeproduct.getFields", httpVerb: "GET" },
      // inventory documents
      document_add: { restMethod: "catalog.document.add", httpVerb: "POST", bodyParam: "fields", bodyWrapper: "fields" },
      document_list: { restMethod: "catalog.document.list", httpVerb: "GET", isList: true, queryParams: ["filter", "select", "order", "start"] },
      document_update: { restMethod: "catalog.document.update", httpVerb: "POST", pathParams: ["inventoryDocumentId"], bodyParam: "fields", bodyWrapper: "fields" },
      document_delete: { restMethod: "catalog.document.delete", httpVerb: "POST", pathParams: ["inventoryDocumentId"] },
      document_conduct: { restMethod: "catalog.document.conduct", httpVerb: "POST", pathParams: ["inventoryDocumentId"], destructive: true },
      document_cancel: { restMethod: "catalog.document.cancel", httpVerb: "POST", pathParams: ["inventoryDocumentId"] },
      document_modeStatus: { restMethod: "catalog.document.mode.status", httpVerb: "GET" },
      document_fields: { restMethod: "catalog.document.getFields", httpVerb: "GET" },
      document_element_add: { restMethod: "catalog.document.element.add", httpVerb: "POST", bodyParam: "fields", bodyWrapper: "fields" },
      document_element_list: { restMethod: "catalog.document.element.list", httpVerb: "GET", isList: true, queryParams: ["filter", "select", "order", "start"] },
      document_element_update: { restMethod: "catalog.document.element.update", httpVerb: "POST", pathParams: ["id"], bodyParam: "fields", bodyWrapper: "fields" },
      document_element_delete: { restMethod: "catalog.document.element.delete", httpVerb: "POST", pathParams: ["id"] },
      document_element_fields: { restMethod: "catalog.document.element.getFields", httpVerb: "GET" },
      documentcontractor_add: { restMethod: "catalog.documentcontractor.add", httpVerb: "POST", bodyParam: "fields", bodyWrapper: "fields" },
      documentcontractor_list: { restMethod: "catalog.documentcontractor.list", httpVerb: "GET", isList: true, queryParams: ["filter", "select", "order", "start"] },
      documentcontractor_delete: { restMethod: "catalog.documentcontractor.delete", httpVerb: "POST", pathParams: ["id"] },
      documentcontractor_fields: { restMethod: "catalog.documentcontractor.getFields", httpVerb: "GET" },
      // product properties
      property_add: { restMethod: "catalog.productProperty.add", httpVerb: "POST", bodyParam: "fields", bodyWrapper: "fields" },
      property_get: { restMethod: "catalog.productProperty.get", httpVerb: "GET", pathParams: ["propertyId"] },
      property_list: { restMethod: "catalog.productProperty.list", httpVerb: "GET", isList: true, queryParams: ["filter", "select", "order", "start"] },
      property_update: { restMethod: "catalog.productProperty.update", httpVerb: "POST", pathParams: ["propertyId"], bodyParam: "fields", bodyWrapper: "fields" },
      property_delete: { restMethod: "catalog.productProperty.delete", httpVerb: "POST", pathParams: ["propertyId"] },
      property_fields: { restMethod: "catalog.productProperty.getFields", httpVerb: "GET" },
      propertyEnum_add: { restMethod: "catalog.productPropertyEnum.add", httpVerb: "POST", bodyParam: "fields", bodyWrapper: "fields" },
      propertyEnum_get: { restMethod: "catalog.productPropertyEnum.get", httpVerb: "GET", pathParams: ["propertyEnumId"] },
      propertyEnum_list: { restMethod: "catalog.productPropertyEnum.list", httpVerb: "GET", isList: true, queryParams: ["filter", "select", "order", "start"] },
      propertyEnum_update: { restMethod: "catalog.productPropertyEnum.update", httpVerb: "POST", pathParams: ["propertyEnumId"], bodyParam: "fields", bodyWrapper: "fields" },
      propertyEnum_delete: { restMethod: "catalog.productPropertyEnum.delete", httpVerb: "POST", pathParams: ["propertyEnumId"] },
      propertyEnum_fields: { restMethod: "catalog.productPropertyEnum.getFields", httpVerb: "GET" },
      propertyFeature_add: { restMethod: "catalog.productPropertyFeature.add", httpVerb: "POST", bodyParam: "fields", bodyWrapper: "fields" },
      propertyFeature_get: { restMethod: "catalog.productPropertyFeature.get", httpVerb: "GET", pathParams: ["id"] },
      propertyFeature_list: { restMethod: "catalog.productPropertyFeature.list", httpVerb: "GET", isList: true, queryParams: ["filter", "select", "order", "start"] },
      propertyFeature_update: { restMethod: "catalog.productPropertyFeature.update", httpVerb: "POST", pathParams: ["id"], bodyParam: "fields", bodyWrapper: "fields" },
      propertyFeature_availableFeatures: { restMethod: "catalog.productPropertyFeature.getAvailableFeaturesByProperty", httpVerb: "GET", pathParams: ["propertyId"] },
      propertyFeature_fields: { restMethod: "catalog.productPropertyFeature.getFields", httpVerb: "GET" },
      propertySection_set: { restMethod: "catalog.productPropertySection.set", httpVerb: "POST", bodyParam: "fields", bodyWrapper: "fields" },
      propertySection_get: { restMethod: "catalog.productPropertySection.get", httpVerb: "GET", pathParams: ["id"] },
      propertySection_list: { restMethod: "catalog.productPropertySection.list", httpVerb: "GET", isList: true, queryParams: ["filter", "select", "order", "start"] },
      // product kinds
      offer_add: { restMethod: "catalog.product.offer.add", httpVerb: "POST", bodyParam: "fields", bodyWrapper: "fields" },
      offer_get: { restMethod: "catalog.product.offer.get", httpVerb: "GET", pathParams: ["id"] },
      offer_list: { restMethod: "catalog.product.offer.list", httpVerb: "GET", isList: true, queryParams: ["filter", "select", "order", "start"] },
      offer_update: { restMethod: "catalog.product.offer.update", httpVerb: "POST", pathParams: ["id"], bodyParam: "fields", bodyWrapper: "fields" },
      offer_delete: { restMethod: "catalog.product.offer.delete", httpVerb: "POST", pathParams: ["id"] },
      offer_fields: { restMethod: "catalog.product.offer.getFieldsByFilter", httpVerb: "GET" },
      sku_add: { restMethod: "catalog.product.sku.add", httpVerb: "POST", bodyParam: "fields", bodyWrapper: "fields" },
      sku_get: { restMethod: "catalog.product.sku.get", httpVerb: "GET", pathParams: ["id"] },
      sku_list: { restMethod: "catalog.product.sku.list", httpVerb: "GET", isList: true, queryParams: ["filter", "select", "order", "start"] },
      sku_update: { restMethod: "catalog.product.sku.update", httpVerb: "POST", pathParams: ["id"], bodyParam: "fields", bodyWrapper: "fields" },
      sku_delete: { restMethod: "catalog.product.sku.delete", httpVerb: "POST", pathParams: ["id"] },
      sku_fields: { restMethod: "catalog.product.sku.getFieldsByFilter", httpVerb: "GET" },
      service_add: { restMethod: "catalog.product.service.add", httpVerb: "POST", bodyParam: "fields", bodyWrapper: "fields" },
      service_get: { restMethod: "catalog.product.service.get", httpVerb: "GET", pathParams: ["id"] },
      service_list: { restMethod: "catalog.product.service.list", httpVerb: "GET", isList: true, queryParams: ["filter", "select", "order", "start"] },
      service_update: { restMethod: "catalog.product.service.update", httpVerb: "POST", pathParams: ["id"], bodyParam: "fields", bodyWrapper: "fields" },
      service_delete: { restMethod: "catalog.product.service.delete", httpVerb: "POST", pathParams: ["id"] },
      service_fields: { restMethod: "catalog.product.service.getFieldsByFilter", httpVerb: "GET" },
      // enums
      enum_getRoundTypes: { restMethod: "catalog.enum.getRoundTypes", httpVerb: "GET" },
      enum_getStoreDocumentTypes: { restMethod: "catalog.enum.getStoreDocumentTypes", httpVerb: "GET" },
    },
    client,
    {
      product_add: "Create a product (NAME required)", product_get: "Get a product by ID", product_list: "List products",
      product_update: "Update product fields", product_delete: "Delete a product (destructive)", product_fields: "Describe product fields",
      section_add: "Create a section", section_get: "Get a section", section_list: "List catalog sections",
      section_update: "Update a section", section_delete: "Delete a section (destructive)", section_fields: "Describe section fields",
      price_add: "Add a price", price_get: "Get a price", price_list: "List prices", price_update: "Update a price",
      price_delete: "Delete a price (destructive)", price_fields: "Describe price fields",
      store_add: "Add a warehouse", store_get: "Get a warehouse", store_list: "List warehouses",
      store_update: "Update a warehouse", store_delete: "Delete a warehouse (destructive)", store_fields: "Describe warehouse fields",
      productrow_add: "Add a product row to an entity", productrow_get: "Get a product row by ID", productrow_list: "List product rows",
      catalog_list: "List trade catalogs", catalog_get: "Get a trade catalog", catalog_isOffers: "Check if a catalog holds variations (offers)",
      catalog_fields: "Describe trade catalog fields",
      priceType_add: "Add a price type", priceType_get: "Get a price type", priceType_list: "List price types",
      priceType_update: "Update a price type", priceType_delete: "Delete a price type (destructive)", priceType_fields: "Describe price type fields",
      measure_add: "Add a measurement unit", measure_get: "Get a measurement unit", measure_list: "List measurement units",
      measure_update: "Update a measurement unit", measure_delete: "Delete a measurement unit (destructive)", measure_fields: "Describe measure fields",
      vat_add: "Add a VAT rate", vat_get: "Get a VAT rate", vat_list: "List VAT rates",
      vat_update: "Update a VAT rate", vat_delete: "Delete a VAT rate (destructive)", vat_fields: "Describe VAT fields",
      ratio_list: "List measurement ratios", ratio_fields: "Describe ratio fields",
      roundingRule_add: "Add a rounding rule", roundingRule_get: "Get a rounding rule", roundingRule_list: "List rounding rules",
      roundingRule_update: "Update a rounding rule", roundingRule_delete: "Delete a rounding rule (destructive)", roundingRule_fields: "Describe rounding rule fields",
      extra_get: "Get an extra charge", extra_list: "List extra charges", extra_fields: "Describe extra charge fields",
      storeProduct_get: "Get a stock record", storeProduct_list: "List stock records", storeProduct_fields: "Describe stock fields",
      document_add: "Add an inventory document", document_list: "List inventory documents",
      document_update: "Update an inventory document", document_delete: "Delete an inventory document (destructive)",
      document_conduct: "Conduct (post) an inventory document", document_cancel: "Cancel conducting a document (destructive)",
      document_modeStatus: "Check warehouse inventory mode", document_fields: "Describe inventory document fields",
      document_element_add: "Add an item to an inventory document", document_element_list: "List document items",
      document_element_update: "Update a document item", document_element_delete: "Delete a document item (destructive)",
      document_element_fields: "Describe document item fields",
      documentcontractor_add: "Add a contractor link", documentcontractor_list: "List contractor links",
      documentcontractor_delete: "Delete a contractor link (destructive)", documentcontractor_fields: "Describe contractor fields",
      property_add: "Add a product property", property_get: "Get a product property", property_list: "List product properties",
      property_update: "Update a product property", property_delete: "Delete a product property (destructive)", property_fields: "Describe property fields",
      propertyEnum_add: "Add a property enum value", propertyEnum_get: "Get a property enum value", propertyEnum_list: "List property enum values",
      propertyEnum_update: "Update a property enum value", propertyEnum_delete: "Delete a property enum value (destructive)", propertyEnum_fields: "Describe enum fields",
      propertyFeature_add: "Add a property feature", propertyFeature_get: "Get a property feature", propertyFeature_list: "List property features",
      propertyFeature_update: "Update a property feature", propertyFeature_availableFeatures: "List available features for a property",
      propertyFeature_fields: "Describe property feature fields",
      propertySection_set: "Set property-section bindings", propertySection_get: "Get a property-section binding", propertySection_list: "List property-section bindings",
      offer_add: "Add a product variation (offer)", offer_get: "Get a variation", offer_list: "List variations",
      offer_update: "Update a variation", offer_delete: "Delete a variation (destructive)", offer_fields: "Describe variation fields",
      sku_add: "Add a SKU head (parent product)", sku_get: "Get a SKU head", sku_list: "List SKU heads",
      sku_update: "Update a SKU head", sku_delete: "Delete a SKU head (destructive)", sku_fields: "Describe SKU head fields",
      service_add: "Add a service", service_get: "Get a service", service_list: "List services",
      service_update: "Update a service", service_delete: "Delete a service (destructive)", service_fields: "Describe service fields",
      enum_getRoundTypes: "List price rounding types", enum_getStoreDocumentTypes: "List inventory document types",
    },
  );
}