import type { Bitrix24ApiClient } from "../../api-client.js";
import type { ToolDefinition } from "../../types.js";
import { createActionTool } from "../framework.js";
import { P } from "../params.js";
import { API_VERSION } from "../../constants.js";

export function createRequisitesTool(client: Bitrix24ApiClient): ToolDefinition {
  return createActionTool(
    "bx24_crm_requisites",
    `Bitrix24 CRM requisites (реквизиты): CRUD, presets, bank details, links, user fields. Methods crm.requisite.*, crm.requisite.preset.*, crm.requisite.bankdetail.*, crm.requisite.link.*, crm.requisite.userfield.* (${API_VERSION}). RU/EN: реквизиты, добавить реквизиты компании, пресет, банковские реквизиты, привязка / requisites, company details, preset, bank details, link.`,
    [
      "add", "get", "list", "update", "delete", "fields",
      "preset_list", "preset_get", "preset_add", "preset_update", "preset_delete", "preset_countries", "preset_fields",
      "bankdetail_add", "bankdetail_get", "bankdetail_list", "bankdetail_update", "bankdetail_delete", "bankdetail_fields",
      "link_add", "link_register", "link_get", "link_list", "link_unregister", "link_fields",
      "userfield_add", "userfield_get", "userfield_list", "userfield_update", "userfield_delete",
    ],
    {
      id: P.id, fields: { type: "object", description: "Requisite fields: ENTITY_TYPE_ID, ENTITY_ID, PRESET_ID, NAME, RQ_INN, RQ_KPP, RQ_COMPANY_NAME, RQ_ADDRESS." },
      filter: P.filter, select: P.select, order: P.order, start: P.start,
      presetId: { type: "string", description: "Requisite preset ID" },
      bankdetailId: { type: "string", description: "Bank detail ID" },
      linkFields: { type: "object", description: "Link fields: ENTITY_TYPE_ID, ENTITY_ID, REQUISITE_ID" },
      userfieldId: P.userfieldId, userfield: { type: "object", description: "User field definition" },
    },
    {
      add: { restMethod: "crm.requisite.add", httpVerb: "POST", bodyParam: "fields", bodyWrapper: "fields" },
      get: { restMethod: "crm.requisite.get", httpVerb: "GET", pathParams: ["id"] },
      list: { restMethod: "crm.requisite.list", httpVerb: "GET", isList: true, queryParams: ["filter", "select", "order", "start"] },
      update: { restMethod: "crm.requisite.update", httpVerb: "POST", pathParams: ["id"], bodyParam: "fields", bodyWrapper: "fields" },
      delete: { restMethod: "crm.requisite.delete", httpVerb: "POST", pathParams: ["id"] },
      fields: { restMethod: "crm.requisite.fields", httpVerb: "GET" },
      preset_list: { restMethod: "crm.requisite.preset.list", httpVerb: "GET" },
      preset_get: { restMethod: "crm.requisite.preset.get", httpVerb: "GET", pathParams: ["presetId"] },
      preset_add: { restMethod: "crm.requisite.preset.add", httpVerb: "POST", bodyParam: "fields", bodyWrapper: "fields" },
      preset_update: { restMethod: "crm.requisite.preset.update", httpVerb: "POST", pathParams: ["presetId"], bodyParam: "fields", bodyWrapper: "fields" },
      preset_delete: { restMethod: "crm.requisite.preset.delete", httpVerb: "POST", pathParams: ["presetId"] },
      preset_countries: { restMethod: "crm.requisite.preset.countries", httpVerb: "GET" },
      preset_fields: { restMethod: "crm.requisite.preset.fields", httpVerb: "GET" },
      bankdetail_add: { restMethod: "crm.requisite.bankdetail.add", httpVerb: "POST", bodyParam: "fields", bodyWrapper: "fields" },
      bankdetail_get: { restMethod: "crm.requisite.bankdetail.get", httpVerb: "GET", pathParams: ["bankdetailId"] },
      bankdetail_list: { restMethod: "crm.requisite.bankdetail.list", httpVerb: "GET", isList: true, queryParams: ["filter", "select", "order", "start"] },
      bankdetail_update: { restMethod: "crm.requisite.bankdetail.update", httpVerb: "POST", pathParams: ["bankdetailId"], bodyParam: "fields", bodyWrapper: "fields" },
      bankdetail_delete: { restMethod: "crm.requisite.bankdetail.delete", httpVerb: "POST", pathParams: ["bankdetailId"] },
      bankdetail_fields: { restMethod: "crm.requisite.bankdetail.fields", httpVerb: "GET" },
      link_add: { restMethod: "crm.requisite.link.add", httpVerb: "POST", bodyParam: "linkFields", bodyWrapper: "fields" },
      link_register: { restMethod: "crm.requisite.link.register", httpVerb: "POST", bodyParam: "linkFields", bodyWrapper: "fields" },
      link_get: { restMethod: "crm.requisite.link.get", httpVerb: "GET", pathParams: ["id"] },
      link_list: { restMethod: "crm.requisite.link.list", httpVerb: "GET", isList: true, queryParams: ["filter", "select", "order", "start"] },
      link_unregister: { restMethod: "crm.requisite.link.unregister", httpVerb: "POST", bodyParam: "linkFields", bodyWrapper: "fields" },
      link_fields: { restMethod: "crm.requisite.link.fields", httpVerb: "GET" },
      userfield_add: { restMethod: "crm.requisite.userfield.add", httpVerb: "POST", bodyParam: "userfield", bodyWrapper: "fields" },
      userfield_get: { restMethod: "crm.requisite.userfield.get", httpVerb: "GET", pathParams: ["userfieldId"] },
      userfield_list: { restMethod: "crm.requisite.userfield.list", httpVerb: "GET" },
      userfield_update: { restMethod: "crm.requisite.userfield.update", httpVerb: "POST", pathParams: ["userfieldId"], bodyParam: "userfield", bodyWrapper: "fields" },
      userfield_delete: { restMethod: "crm.requisite.userfield.delete", httpVerb: "POST", pathParams: ["userfieldId"] },
    },
    client,
    {
      add: "Create requisite (INN/KPP/etc.) for a company/contact", get: "Get a requisite by ID",
      list: "List requisites", update: "Update requisite fields", delete: "Delete a requisite (destructive)", fields: "Describe requisite fields",
      preset_list: "List requisite presets", preset_get: "Get a preset by ID",
      preset_add: "Add a requisite preset", preset_update: "Update a preset", preset_delete: "Delete a preset (destructive)",
      preset_countries: "List preset countries", preset_fields: "Describe preset fields",
      bankdetail_add: "Add bank details", bankdetail_get: "Get bank details", bankdetail_list: "List bank details",
      bankdetail_update: "Update bank details", bankdetail_delete: "Delete bank details (destructive)", bankdetail_fields: "Describe bank detail fields",
      link_add: "Link a requisite to an entity", link_register: "Register a requisite link",
      link_get: "Get a requisite link", link_list: "List requisite links",
      link_unregister: "Unregister a requisite link (destructive)", link_fields: "Describe link fields",
      userfield_add: "Create a requisite user field", userfield_get: "Get a requisite user field",
      userfield_list: "List requisite user fields", userfield_update: "Update a requisite user field",
      userfield_delete: "Delete a requisite user field (destructive)",
    },
  );
}