import type { Bitrix24ApiClient } from "../../api-client.js";
import type { ToolDefinition } from "../../types.js";
import { createActionTool } from "../framework.js";
import { P } from "../params.js";
import { API_VERSION } from "../../constants.js";

export function createBotsTool(client: Bitrix24ApiClient): ToolDefinition {
  return createActionTool(
    "bx24_bots",
    `Bitrix24 chat bots v2 (чат-боты): bot registration, chats, messages, reactions, commands, files, events. Methods imbot.v2.* (${API_VERSION}). RU/EN: чат-бот, бот, зарегистрировать бота, команда, реакция / chat bot, register bot, command, reaction.`,
    [
      "bot_register", "bot_update", "bot_get", "bot_list", "bot_unregister",
      "chat_add", "chat_get", "chat_update", "chat_leave", "chat_setOwner",
      "chat_user_add", "chat_user_delete", "chat_user_list", "chat_manager_add", "chat_manager_delete",
      "message_send", "message_update", "message_delete", "message_read", "message_get", "message_getContext",
      "reaction_add", "reaction_delete",
      "command_register", "command_update", "command_list", "command_unregister", "command_answer",
      "file_upload", "file_download", "event_get",
    ],
    {
      botId: P.botId,
      code: { type: "string", description: "Bot code (unique identifier)" },
      clientId: { type: "string", description: "App client_id (for bot registration)" },
      fields: { type: "object", description: "Bot/chat/message/command fields (per Bitrix24 docs for the method)" },
      chatId: P.chatId,
      messageId: P.messageId,
      reactionId: P.reactionId,
      commandId: P.commandId,
      filter: P.filter, select: P.select, order: P.order, start: P.start,
      file: { type: "object", description: "File to upload: NAME, CONTENT base64" },
    },
    {
      bot_register: { restMethod: "imbot.v2.Bot.register", httpVerb: "POST", bodyParam: "fields", bodyWrapper: "fields" },
      bot_update: { restMethod: "imbot.v2.Bot.update", httpVerb: "POST", pathParams: ["botId"], bodyParam: "fields", bodyWrapper: "fields" },
      bot_get: { restMethod: "imbot.v2.Bot.get", httpVerb: "GET", pathParams: ["botId"] },
      bot_list: { restMethod: "imbot.v2.Bot.list", httpVerb: "GET", queryParams: ["filter", "select", "order", "start"] },
      bot_unregister: { restMethod: "imbot.v2.Bot.unregister", httpVerb: "POST", pathParams: ["botId"] },
      chat_add: { restMethod: "imbot.v2.Chat.add", httpVerb: "POST", bodyParam: "fields", bodyWrapper: "fields" },
      chat_get: { restMethod: "imbot.v2.Chat.get", httpVerb: "GET", pathParams: ["chatId"] },
      chat_update: { restMethod: "imbot.v2.Chat.update", httpVerb: "POST", pathParams: ["chatId"], bodyParam: "fields", bodyWrapper: "fields" },
      chat_leave: { restMethod: "imbot.v2.Chat.leave", httpVerb: "POST", pathParams: ["chatId"] },
      chat_setOwner: { restMethod: "imbot.v2.Chat.setOwner", httpVerb: "POST", pathParams: ["chatId"], bodyParam: "fields", bodyWrapper: "fields" },
      chat_user_add: { restMethod: "imbot.v2.Chat.User.add", httpVerb: "POST", pathParams: ["chatId"], bodyParam: "fields", bodyWrapper: "fields" },
      chat_user_delete: { restMethod: "imbot.v2.Chat.User.delete", httpVerb: "POST", pathParams: ["chatId"], bodyParam: "fields", bodyWrapper: "fields" },
      chat_user_list: { restMethod: "imbot.v2.Chat.User.list", httpVerb: "GET", pathParams: ["chatId"] },
      chat_manager_add: { restMethod: "imbot.v2.Chat.Manager.add", httpVerb: "POST", pathParams: ["chatId"], bodyParam: "fields", bodyWrapper: "fields" },
      chat_manager_delete: { restMethod: "imbot.v2.Chat.Manager.delete", httpVerb: "POST", pathParams: ["chatId"], bodyParam: "fields", bodyWrapper: "fields" },
      message_send: { restMethod: "imbot.v2.Chat.Message.send", httpVerb: "POST", bodyParam: "fields", bodyWrapper: "fields" },
      message_update: { restMethod: "imbot.v2.Chat.Message.update", httpVerb: "POST", pathParams: ["messageId"], bodyParam: "fields", bodyWrapper: "fields" },
      message_delete: { restMethod: "imbot.v2.Chat.Message.delete", httpVerb: "POST", pathParams: ["messageId"] },
      message_read: { restMethod: "imbot.v2.Chat.Message.read", httpVerb: "POST", pathParams: ["messageId"] },
      message_get: { restMethod: "imbot.v2.Chat.Message.get", httpVerb: "GET", pathParams: ["messageId"] },
      message_getContext: { restMethod: "imbot.v2.Chat.Message.getContext", httpVerb: "GET", pathParams: ["messageId"] },
      reaction_add: { restMethod: "imbot.v2.Chat.Message.Reaction.add", httpVerb: "POST", pathParams: ["messageId"], bodyParam: "reactionId", bodyWrapper: "reaction" },
      reaction_delete: { restMethod: "imbot.v2.Chat.Message.Reaction.delete", httpVerb: "POST", pathParams: ["messageId"], bodyParam: "reactionId", bodyWrapper: "reaction" },
      command_register: { restMethod: "imbot.v2.Command.register", httpVerb: "POST", bodyParam: "fields", bodyWrapper: "fields" },
      command_update: { restMethod: "imbot.v2.Command.update", httpVerb: "POST", pathParams: ["commandId"], bodyParam: "fields", bodyWrapper: "fields" },
      command_list: { restMethod: "imbot.v2.Command.list", httpVerb: "GET", queryParams: ["filter", "select", "order", "start"] },
      command_unregister: { restMethod: "imbot.v2.Command.unregister", httpVerb: "POST", pathParams: ["commandId"] },
      command_answer: { restMethod: "imbot.v2.Command.answer", httpVerb: "POST", bodyParam: "fields", bodyWrapper: "fields" },
      file_upload: { restMethod: "imbot.v2.File.upload", httpVerb: "POST", bodyParam: "file", bodyWrapper: "fields" },
      file_download: { restMethod: "imbot.v2.File.download", httpVerb: "GET", pathParams: ["messageId"] },
      event_get: { restMethod: "imbot.v2.Event.get", httpVerb: "GET", queryParams: ["filter", "select", "order", "start"] },
    },
    client,
    {
      bot_register: "Register a chat bot", bot_update: "Update bot properties", bot_get: "Get bot info",
      bot_list: "List bots of the app", bot_unregister: "Unregister/remove a bot (destructive)",
      chat_add: "Create a group chat (bot-hosted)", chat_get: "Get chat info", chat_update: "Update chat properties",
      chat_leave: "Bot leaves a chat (destructive)", chat_setOwner: "Change chat owner",
      chat_user_add: "Add a member to a chat", chat_user_delete: "Remove a member (destructive)",
      chat_user_list: "List chat members", chat_manager_add: "Add a chat manager", chat_manager_delete: "Remove a chat manager (destructive)",
      message_send: "Bot sends a message", message_update: "Update a bot message", message_delete: "Delete a bot message (destructive)",
      message_read: "Mark a message read", message_get: "Get a message by ID", message_getContext: "Get message context window",
      reaction_add: "Add a reaction to a message", reaction_delete: "Remove a reaction (destructive)",
      command_register: "Register a slash command", command_update: "Update a command",
      command_list: "List bot commands", command_unregister: "Unregister a command (destructive)", command_answer: "Respond to a command",
      file_upload: "Upload a file to a chat", file_download: "Get a file download link",
      event_get: "Poll for bot events",
    },
  );
}