import type { Bitrix24ApiClient } from "../../api-client.js";
import type { ToolDefinition } from "../../types.js";
import { createActionTool } from "../framework.js";
import { P } from "../params.js";
import { API_VERSION } from "../../constants.js";

export function createImTool(client: Bitrix24ApiClient): ToolDefinition {
  return createActionTool(
    "bx24_im",
    `Bitrix24 messenger: messages, notifications, user info, search, counters, recent. Methods im.message.*, im.notify.*, im.user.*, im.search.*, im.counters.*, im.recent.* (${API_VERSION}). RU/EN: сообщение, написать, уведомление, поиск сообщений, счётчики, недавние / message, notify, search messages, counters, recent.`,
    ["message_add", "message_update", "message_delete", "message_get", "message_like", "message_share", "message_command", "dialog_get", "dialog_messages_list", "dialog_messages_search", "dialog_read", "dialog_unread", "dialog_read_all", "dialog_typing", "dialog_mark", "dialog_users", "notify_personal_add", "notify_system_add", "notify_delete", "notify_get", "notify_read", "notify_read_list", "notify_read_all", "notify_answer", "notify_confirm", "notify_history_search", "user_get", "user_list", "user_status_set", "user_status_get", "search_message", "search_user", "search_chat_list", "search_department_list", "search_last_add", "search_last_get", "search_last_delete", "counters_get", "recent_list", "recent_pinned", "recent_unpin", "recent_hide", "department_get", "department_managers_get", "department_employees_get", "department_colleagues_list", "v2_file_upload", "v2_file_download", "v2_event_subscribe", "v2_event_get", "v2_event_unsubscribe", "bot_list"],
    {
      DIALOG_ID: { type: "string", description: "Dialog ID: chatNNN or numeric user ID" },
      MESSAGE_ID: { type: "string", description: "Message ID" },
      MESSAGE: { type: "string", description: "Message text" },
      SYSTEM: { type: "boolean", description: "Send as system message" },
      TO: { type: "string", description: "Recipient user ID (notify)" },
      ID: { type: "string", description: "Entity ID (notify/message/department)" },
      IDS: { type: "array", items: { type: "string" }, description: "Array of IDs" },
      USER_ID: { type: "string", description: "User ID" },
      LIMIT: { type: "integer", minimum: 1, description: "Page size" },
      LAST_ID: { type: "string", description: "Last message ID for pagination" },
      SEARCH: { type: "string", description: "Search string" },
      STATUS: { type: "string", description: "User status (online/away/dnd)" },
      file: { type: "object", description: "File to upload: NAME, CONTENT base64, CHAT_ID/DIALOG_ID" },
      filter: P.filter, select: P.select, order: P.order, start: P.start,
    },
    {
      message_add: { restMethod: "im.message.add", httpVerb: "POST", rawBody: true },
      message_update: { restMethod: "im.message.update", httpVerb: "POST", rawBody: true },
      message_delete: { restMethod: "im.message.delete", httpVerb: "POST", pathParams: ["MESSAGE_ID"] },
      message_get: { restMethod: "im.message.get", httpVerb: "GET", pathParams: ["MESSAGE_ID"] },
      message_like: { restMethod: "im.message.like", httpVerb: "POST", pathParams: ["MESSAGE_ID"] },
      message_share: { restMethod: "im.message.share", httpVerb: "POST", rawBody: true },
      message_command: { restMethod: "im.message.command", httpVerb: "POST", rawBody: true },
      dialog_get: { restMethod: "im.dialog.get", httpVerb: "POST", pathParams: ["DIALOG_ID"] },
      dialog_messages_list: { restMethod: "im.dialog.messages.list", httpVerb: "GET", queryParams: ["DIALOG_ID", "LIMIT", "LAST_ID"] },
      dialog_messages_search: { restMethod: "im.dialog.messages.search", httpVerb: "GET", queryParams: ["DIALOG_ID", "SEARCH", "LIMIT"] },
      dialog_read: { restMethod: "im.dialog.read", httpVerb: "POST", pathParams: ["DIALOG_ID"] },
      dialog_unread: { restMethod: "im.dialog.unread", httpVerb: "POST", pathParams: ["DIALOG_ID"] },
      dialog_read_all: { restMethod: "im.dialog.read.all", httpVerb: "POST" },
      dialog_typing: { restMethod: "im.dialog.typing.status", httpVerb: "POST", pathParams: ["DIALOG_ID"] },
      dialog_mark: { restMethod: "im.message.attention", httpVerb: "POST", pathParams: ["DIALOG_ID", "MESSAGE_ID"] },
      dialog_users: { restMethod: "im.dialog.users.list", httpVerb: "GET", pathParams: ["DIALOG_ID"] },
      notify_personal_add: { restMethod: "im.notify.add", httpVerb: "POST", rawBody: true },
      notify_system_add: { restMethod: "im.notify.system.add", httpVerb: "POST", rawBody: true },
      notify_delete: { restMethod: "im.notify.delete", httpVerb: "POST", pathParams: ["ID"] },
      notify_get: { restMethod: "im.notify.get", httpVerb: "GET" },
      notify_read: { restMethod: "im.notify.read", httpVerb: "POST", pathParams: ["ID"] },
      notify_read_list: { restMethod: "im.notify.read.list", httpVerb: "POST", bodyParam: "IDS", bodyWrapper: "ids" },
      notify_read_all: { restMethod: "im.notify.read.all", httpVerb: "POST" },
      notify_answer: { restMethod: "im.notify.answer", httpVerb: "POST", pathParams: ["ID"], bodyParam: "MESSAGE", bodyWrapper: "answerText" },
      notify_confirm: { restMethod: "im.notify.confirm", httpVerb: "POST", pathParams: ["ID"], bodyParam: "MESSAGE", bodyWrapper: "action" },
      notify_history_search: { restMethod: "im.notify.history.search", httpVerb: "GET", queryParams: ["SEARCH", "LIMIT"] },
      user_get: { restMethod: "im.user.get", httpVerb: "GET", pathParams: ["ID"] },
      user_list: { restMethod: "im.user.list", httpVerb: "GET", queryParams: ["IDS", "LAST_ID", "LIMIT"] },
      user_status_set: { restMethod: "im.user.status.set", httpVerb: "POST", pathParams: ["STATUS"] },
      user_status_get: { restMethod: "im.user.status.get", httpVerb: "GET", pathParams: ["USER_ID"] },
      search_message: { restMethod: "im.search.message.list", httpVerb: "GET", queryParams: ["SEARCH", "LIMIT"] },
      search_user: { restMethod: "im.search.user.list", httpVerb: "GET", queryParams: ["SEARCH", "LIMIT"] },
      search_chat_list: { restMethod: "im.search.chat.list", httpVerb: "GET", queryParams: ["SEARCH", "LIMIT"] },
      search_department_list: { restMethod: "im.search.department.list", httpVerb: "GET", queryParams: ["SEARCH", "LIMIT"] },
      search_last_add: { restMethod: "im.search.last.add", httpVerb: "POST", rawBody: true },
      search_last_get: { restMethod: "im.search.last.get", httpVerb: "GET" },
      search_last_delete: { restMethod: "im.search.last.delete", httpVerb: "POST", pathParams: ["ID"] },
      counters_get: { restMethod: "im.counters.get", httpVerb: "GET" },
      recent_list: { restMethod: "im.recent.list", httpVerb: "GET", queryParams: ["LIMIT", "LAST_ID"] },
      recent_pinned: { restMethod: "im.recent.pin", httpVerb: "POST", pathParams: ["DIALOG_ID"] },
      recent_unpin: { restMethod: "im.recent.unpin", httpVerb: "POST", pathParams: ["DIALOG_ID"] },
      recent_hide: { restMethod: "im.recent.hide", httpVerb: "POST", pathParams: ["DIALOG_ID"] },
      department_get: { restMethod: "im.department.get", httpVerb: "GET", pathParams: ["ID"] },
      department_managers_get: { restMethod: "im.department.managers.get", httpVerb: "GET", pathParams: ["ID"] },
      department_employees_get: { restMethod: "im.department.employees.get", httpVerb: "GET", pathParams: ["ID"] },
      department_colleagues_list: { restMethod: "im.department.colleagues.list", httpVerb: "GET" },
      v2_file_upload: { restMethod: "im.v2.File.upload", httpVerb: "POST", bodyParam: "file", bodyWrapper: "fields" },
      v2_file_download: { restMethod: "im.v2.File.download", httpVerb: "GET", pathParams: ["MESSAGE_ID"] },
      v2_event_subscribe: { restMethod: "im.v2.Event.subscribe", httpVerb: "POST" },
      v2_event_get: { restMethod: "im.v2.Event.get", httpVerb: "GET" },
      v2_event_unsubscribe: { restMethod: "im.v2.Event.unsubscribe", httpVerb: "POST" },
      bot_list: { restMethod: "imbot.bot.list", httpVerb: "GET" },
    },
    client,
    {
      message_add: "Send a message (DIALOG_ID, MESSAGE)", message_update: "Update a message (MESSAGE_ID, MESSAGE)",
      message_delete: "Delete a message (destructive)", message_get: "Get a message by ID",
      message_like: "Toggle 'Like' on a message", message_share: "Create a chat/task/post from a message",
      message_command: "Execute a chat-bot command on a message",
      dialog_get: "Get dialog info", dialog_messages_list: "List dialog message history",
      dialog_messages_search: "Search messages in a dialog", dialog_read: "Mark dialog read",
      dialog_unread: "Mark dialog unread", dialog_read_all: "Mark all user dialogs read",
      dialog_typing: "Send typing status", dialog_mark: "Mark a message for attention",
      dialog_users: "List dialog users",
      notify_personal_add: "Send a personal notification (TO, MESSAGE)", notify_system_add: "Send a system notification",
      notify_delete: "Delete a notification (destructive)", notify_get: "Get user notifications",
      notify_read: "Mark a notification read/unread", notify_read_list: "Mark notifications read by IDs",
      notify_read_all: "Mark all notifications read", notify_answer: "Reply to a notification with a quick answer",
      notify_confirm: "Interact with notification buttons", notify_history_search: "Search notification history",
      user_get: "Get IM user info", user_list: "List IM users by IDs",
      user_status_set: "Set user status (online/away/dnd)", user_status_get: "Get user status",
      search_message: "Search messages", search_user: "Search users in IM",
      search_chat_list: "Search chats by name", search_department_list: "Search departments",
      search_last_add: "Add a search history entry", search_last_get: "Get search history", search_last_delete: "Delete a search history entry (destructive)",
      counters_get: "Get chat/message counters", recent_list: "List recent dialogs",
      recent_pinned: "Pin a recent dialog", recent_unpin: "Unpin a recent dialog", recent_hide: "Hide a recent dialog",
      department_get: "Get department info (IM)", department_managers_get: "Get department managers",
      department_employees_get: "Get department employees", department_colleagues_list: "List user colleagues",
      v2_file_upload: "Upload a file to a chat (v2 API)", v2_file_download: "Get a file download URL (v2 API)",
      v2_event_subscribe: "Subscribe user to messenger events (v2 API)", v2_event_get: "Get accumulated messenger events (v2 API)",
      v2_event_unsubscribe: "Stop recording messenger events (v2 API)",
      bot_list: "List available bots",
    },
  );
}