import type { Bitrix24ApiClient } from "../../api-client.js";
import type { ToolDefinition } from "../../types.js";
import { createActionTool } from "../framework.js";
import { P } from "../params.js";
import { API_VERSION } from "../../constants.js";

export function createTasksTool(client: Bitrix24ApiClient): ToolDefinition {
  return createActionTool(
    "bx24_tasks",
    `Bitrix24 tasks: full lifecycle, checklists, comments, elapsed, flows, stages, planner. Methods tasks.task.*, task.checklistitem.*, task.commentitem.*, task.elapseditem.*, tasks.flow.Flow.*, task.planner.*, task.dependence.* (${API_VERSION}). RU/EN: задача, поставить задачу, мои задачи, выполнить, делегировать, отложить, чеклист, комментарий, затраченное время / task, my tasks, complete, delegate, defer, checklist, comment, elapsed.`,
    ["add", "update", "get", "list", "delete", "start", "pause", "defer", "complete", "renew", "delegate", "approve", "disapprove", "count", "getFields", "files_attach", "history_list", "result_add", "result_list", "addToFlow", "moveToStage", "checklist_add", "checklist_get", "checklist_list", "checklist_update", "checklist_delete", "checklist_complete", "comment_add", "comment_list", "comment_update", "comment_delete", "elapsed_add"],
    {
      taskId: P.taskId, userId: P.userId,
      fields: { type: "object", description: "Task fields: TITLE, DESCRIPTION, RESPONSIBLE_ID, DEADLINE, GROUP_ID, PRIORITY, STATUS, TAGS, ACCOMPLICES, AUDITORS." },
      filter: { type: "object", description: "Task filter: RESPONSIBLE_ID, STATUS (-1 not done), >=DEADLINE, GROUP_ID" },
      select: P.select, order: P.order, start: P.start,
      checklistFields: { type: "object", description: "Checklist item: TITLE, IS_COMPLETE" },
      commentText: { type: "string", description: "Comment text" },
      commentId: { type: "string", description: "Comment ID" },
      elapsedFields: { type: "object", description: "Elapsed: MINUTES, COMMENT, USER_ID, DATE" },
      flowId: { type: "string", description: "Tasks flow ID" },
      stageId: { type: "string", description: "Task stage ID" },
    },
    {
      add: { restMethod: "tasks.task.add", httpVerb: "POST", bodyParam: "fields", bodyWrapper: "fields" },
      update: { restMethod: "tasks.task.update", httpVerb: "POST", pathParams: ["taskId"], bodyParam: "fields", bodyWrapper: "fields" },
      get: { restMethod: "tasks.task.get", httpVerb: "POST", pathParams: ["taskId"] },
      list: { restMethod: "tasks.task.list", httpVerb: "GET", isList: true, queryParams: ["filter", "select", "order", "start"] },
      delete: { restMethod: "tasks.task.delete", httpVerb: "POST", pathParams: ["taskId"] },
      start: { restMethod: "tasks.task.start", httpVerb: "POST", pathParams: ["taskId"] },
      pause: { restMethod: "tasks.task.pause", httpVerb: "POST", pathParams: ["taskId"] },
      defer: { restMethod: "tasks.task.defer", httpVerb: "POST", pathParams: ["taskId"] },
      complete: { restMethod: "tasks.task.complete", httpVerb: "POST", pathParams: ["taskId"] },
      renew: { restMethod: "tasks.task.renew", httpVerb: "POST", pathParams: ["taskId"] },
      delegate: { restMethod: "tasks.task.delegate", httpVerb: "POST", pathParams: ["taskId"], bodyParam: "userId", bodyWrapper: "userId" },
      approve: { restMethod: "tasks.task.approve", httpVerb: "POST", pathParams: ["taskId"] },
      disapprove: { restMethod: "tasks.task.disapprove", httpVerb: "POST", pathParams: ["taskId"] },
      count: { restMethod: "tasks.task.list", httpVerb: "GET", queryParams: ["filter", "select"] },
      getFields: { restMethod: "tasks.task.getFields", httpVerb: "GET" },
      files_attach: { restMethod: "task.file.attach", httpVerb: "POST", pathParams: ["taskId"] },
      history_list: { restMethod: "tasks.task.history.list", httpVerb: "GET", pathParams: ["taskId"] },
      result_add: { restMethod: "task.result.add", httpVerb: "POST", pathParams: ["taskId"], bodyParam: "commentText", bodyWrapper: "fields" },
      result_list: { restMethod: "task.result.list", httpVerb: "GET", pathParams: ["taskId"] },
      addToFlow: { restMethod: "tasks.flow.Flow.addTask", httpVerb: "POST", pathParams: ["flowId", "taskId"] },
      moveToStage: { restMethod: "task.stages.moveTask", httpVerb: "POST", pathParams: ["taskId", "stageId"] },
      checklist_add: { restMethod: "task.checklistitem.add", httpVerb: "POST", pathParams: ["taskId"], bodyParam: "checklistFields", bodyWrapper: "fields" },
      checklist_get: { restMethod: "task.checklistitem.get", httpVerb: "POST", pathParams: ["taskId", "id"] },
      checklist_list: { restMethod: "task.checklistitem.list", httpVerb: "POST", pathParams: ["taskId"] },
      checklist_update: { restMethod: "task.checklistitem.update", httpVerb: "POST", pathParams: ["taskId", "id"], bodyParam: "checklistFields", bodyWrapper: "fields" },
      checklist_delete: { restMethod: "task.checklistitem.delete", httpVerb: "POST", pathParams: ["taskId", "id"] },
      checklist_complete: { restMethod: "task.checklistitem.complete", httpVerb: "POST", pathParams: ["taskId", "id"] },
      comment_add: { restMethod: "task.commentitem.add", httpVerb: "POST", pathParams: ["taskId"], bodyParam: "commentText", bodyWrapper: "fields" },
      comment_list: { restMethod: "task.commentitem.list", httpVerb: "GET", pathParams: ["taskId"] },
      comment_update: { restMethod: "task.commentitem.update", httpVerb: "POST", pathParams: ["taskId", "commentId"], bodyParam: "commentText", bodyWrapper: "fields" },
      comment_delete: { restMethod: "task.commentitem.delete", httpVerb: "POST", pathParams: ["taskId", "commentId"] },
      elapsed_add: { restMethod: "task.elapseditem.add", httpVerb: "POST", pathParams: ["taskId"], bodyParam: "elapsedFields", bodyWrapper: "fields" },
    },
    client,
    {
      add: "Create a task (TITLE required)", update: "Update task fields", get: "Get a task by ID",
      list: "List/filter tasks (my tasks: RESPONSIBLE_ID+STATUS=-1)", delete: "Delete a task (destructive)",
      start: "Start a task", pause: "Pause a task", defer: "Defer a task", complete: "Complete a task", renew: "Renew a completed task",
      delegate: "Delegate a task (userId)", approve: "Approve a task result", disapprove: "Disapprove a task result",
      count: "Count tasks by filter", getFields: "Describe task fields", files_attach: "Attach a file to a task",
      history_list: "List task history", result_add: "Add a task result", result_list: "List task results",
      addToFlow: "Add a task to a flow", moveToStage: "Move a task to a stage",
      checklist_add: "Add a checklist item", checklist_get: "Get a checklist item", checklist_list: "List checklist items",
      checklist_update: "Update a checklist item", checklist_delete: "Delete a checklist item (destructive)",
      checklist_complete: "Mark a checklist item complete",
      comment_add: "Add a comment to a task", comment_list: "List task comments",
      comment_update: "Update a comment", comment_delete: "Delete a comment (destructive)",
      elapsed_add: "Add elapsed time to a task",
    },
  );
}