import type { Bitrix24ApiClient } from "../../api-client.js";
import type { ToolDefinition } from "../../types.js";
import { createActionTool } from "../framework.js";
import { P } from "../params.js";
import { API_VERSION } from "../../constants.js";

export function createTasksTool(client: Bitrix24ApiClient): ToolDefinition {
  return createActionTool(
    "bx24_tasks",
    `Bitrix24 tasks: full lifecycle, checklists, comments, elapsed, flows, stages, planner. Methods tasks.task.*, task.checklistitem.*, task.commentitem.*, task.elapseditem.*, tasks.flow.Flow.*, task.planner.*, task.dependence.* (${API_VERSION}). RU/EN: задача, поставить задачу, мои задачи, выполнить, делегировать, отложить, чеклист, комментарий, затраченное время / task, my tasks, complete, delegate, defer, checklist, comment, elapsed.`,
    ["add", "update", "get", "list", "delete", "start", "pause", "defer", "complete", "renew", "delegate", "approve", "disapprove", "count", "getFields", "files_attach", "history_list", "result_add", "result_list", "result_update", "result_delete", "addToFlow", "moveToStage", "checklist_add", "checklist_get", "checklist_list", "checklist_update", "checklist_delete", "checklist_complete", "checklist_moveafteritem", "checklist_renew", "comment_add", "comment_list", "comment_update", "comment_delete", "elapsed_add", "elapsed_update", "elapsed_get", "elapsed_list", "elapsed_delete", "flow_create", "flow_get", "flow_update", "flow_delete", "flow_isExists", "flow_activate", "flow_pin", "stage_add", "stage_get", "stage_update", "stage_delete", "stage_canMoveTask", "planner_getList", "dependence_add", "dependence_delete", "userfield_add", "userfield_update", "userfield_get", "userfield_list", "userfield_delete"],
    {
      taskId: P.taskId, userId: P.userId,
      fields: { type: "object", description: "Task fields: TITLE, DESCRIPTION, RESPONSIBLE_ID, DEADLINE, GROUP_ID, PRIORITY, STATUS, TAGS, ACCOMPLICES, AUDITORS." },
      filter: { type: "object", description: "Task filter: RESPONSIBLE_ID, STATUS (-1 not done), >=DEADLINE, GROUP_ID" },
      select: P.select, order: P.order, start: P.start,
      checklistFields: { type: "object", description: "Checklist item: TITLE, IS_COMPLETE" },
      commentText: { type: "string", description: "Comment text" },
      commentId: { type: "string", description: "Comment ID" },
      elapsedFields: { type: "object", description: "Elapsed: MINUTES, COMMENT, USER_ID, DATE" },
      flowId: { type: "string", description: "Tasks flow ID" },
      flowFields: { type: "object", description: "Flow fields: NAME, TYPE, RESPONSIBLE_ID, ..." },
      stageId: { type: "string", description: "Task stage ID" },
      stageFields: { type: "object", description: "Kanban stage fields: TITLE, COLOR" },
      resultId: { type: "string", description: "Task result ID" },
      resultFields: { type: "object", description: "Task result fields" },
      dependsOnId: { type: "string", description: "ID of the task this one depends on" },
      userfield: { type: "object", description: "Task user field definition: FIELD_NAME, USER_TYPE_ID, LABEL" },
      userfieldId: P.userfieldId,
    },
    {
      add: { restMethod: "tasks.task.add", httpVerb: "POST", bodyParam: "fields", bodyWrapper: "fields" },
      update: { restMethod: "tasks.task.update", httpVerb: "POST", pathParams: ["taskId"], bodyParam: "fields", bodyWrapper: "fields" },
      get: { restMethod: "tasks.task.get", httpVerb: "POST", pathParams: ["taskId"] },
      list: { restMethod: "tasks.task.list", httpVerb: "GET", isList: true, queryParams: ["filter", "select", "order", "start"] },
      delete: { restMethod: "tasks.task.delete", httpVerb: "POST", pathParams: ["taskId"] },
      start: { restMethod: "tasks.task.start", httpVerb: "POST", pathParams: ["taskId"] },
      pause: { restMethod: "tasks.task.pause", httpVerb: "POST", pathParams: ["taskId"] },
      defer: { restMethod: "tasks.task.defer", httpVerb: "POST", pathParams: ["taskId"] },
      complete: { restMethod: "tasks.task.complete", httpVerb: "POST", pathParams: ["taskId"] },
      renew: { restMethod: "tasks.task.renew", httpVerb: "POST", pathParams: ["taskId"] },
      delegate: { restMethod: "tasks.task.delegate", httpVerb: "POST", pathParams: ["taskId"], bodyParam: "userId", bodyWrapper: "userId" },
      approve: { restMethod: "tasks.task.approve", httpVerb: "POST", pathParams: ["taskId"] },
      disapprove: { restMethod: "tasks.task.disapprove", httpVerb: "POST", pathParams: ["taskId"] },
      count: { restMethod: "tasks.task.list", httpVerb: "GET", queryParams: ["filter", "select"] },
      getFields: { restMethod: "tasks.task.getFields", httpVerb: "GET" },
      files_attach: { restMethod: "task.file.attach", httpVerb: "POST", pathParams: ["taskId"] },
      history_list: { restMethod: "tasks.task.history.list", httpVerb: "GET", pathParams: ["taskId"] },
      result_add: { restMethod: "task.result.add", httpVerb: "POST", pathParams: ["taskId"], bodyParam: "commentText", bodyWrapper: "fields" },
      result_list: { restMethod: "task.result.list", httpVerb: "GET", pathParams: ["taskId"] },
      result_update: { restMethod: "tasks.task.result.update", httpVerb: "POST", pathParams: ["resultId"], bodyParam: "resultFields", bodyWrapper: "fields" },
      result_delete: { restMethod: "tasks.task.result.delete", httpVerb: "POST", pathParams: ["resultId"] },
      addToFlow: { restMethod: "tasks.flow.Flow.addTask", httpVerb: "POST", pathParams: ["flowId", "taskId"] },
      moveToStage: { restMethod: "task.stages.moveTask", httpVerb: "POST", pathParams: ["taskId", "stageId"] },
      checklist_add: { restMethod: "task.checklistitem.add", httpVerb: "POST", pathParams: ["taskId"], bodyParam: "checklistFields", bodyWrapper: "fields" },
      checklist_get: { restMethod: "task.checklistitem.get", httpVerb: "POST", pathParams: ["taskId", "id"] },
      checklist_list: { restMethod: "task.checklistitem.list", httpVerb: "POST", pathParams: ["taskId"] },
      checklist_update: { restMethod: "task.checklistitem.update", httpVerb: "POST", pathParams: ["taskId", "id"], bodyParam: "checklistFields", bodyWrapper: "fields" },
      checklist_delete: { restMethod: "task.checklistitem.delete", httpVerb: "POST", pathParams: ["taskId", "id"] },
      checklist_complete: { restMethod: "task.checklistitem.complete", httpVerb: "POST", pathParams: ["taskId", "id"] },
      checklist_moveafteritem: { restMethod: "task.checklistitem.moveafteritem", httpVerb: "POST", pathParams: ["taskId", "id"], bodyParam: "checklistFields", bodyWrapper: "fields" },
      checklist_renew: { restMethod: "task.checklistitem.renew", httpVerb: "POST", pathParams: ["taskId", "id"] },
      comment_add: { restMethod: "task.commentitem.add", httpVerb: "POST", pathParams: ["taskId"], bodyParam: "commentText", bodyWrapper: "fields" },
      comment_list: { restMethod: "task.commentitem.list", httpVerb: "GET", pathParams: ["taskId"] },
      comment_update: { restMethod: "task.commentitem.update", httpVerb: "POST", pathParams: ["taskId", "commentId"], bodyParam: "commentText", bodyWrapper: "fields" },
      comment_delete: { restMethod: "task.commentitem.delete", httpVerb: "POST", pathParams: ["taskId", "commentId"] },
      elapsed_add: { restMethod: "task.elapseditem.add", httpVerb: "POST", pathParams: ["taskId"], bodyParam: "elapsedFields", bodyWrapper: "fields" },
      elapsed_update: { restMethod: "task.elapseditem.update", httpVerb: "POST", pathParams: ["taskId", "id"], bodyParam: "elapsedFields", bodyWrapper: "fields" },
      elapsed_get: { restMethod: "task.elapseditem.get", httpVerb: "POST", pathParams: ["taskId", "id"] },
      elapsed_list: { restMethod: "task.elapseditem.getlist", httpVerb: "POST", pathParams: ["taskId"] },
      elapsed_delete: { restMethod: "task.elapseditem.delete", httpVerb: "POST", pathParams: ["taskId", "id"] },
      flow_create: { restMethod: "tasks.flow.Flow.create", httpVerb: "POST", bodyParam: "flowFields", bodyWrapper: "fields" },
      flow_get: { restMethod: "tasks.flow.Flow.get", httpVerb: "GET", pathParams: ["flowId"] },
      flow_update: { restMethod: "tasks.flow.Flow.update", httpVerb: "POST", pathParams: ["flowId"], bodyParam: "flowFields", bodyWrapper: "fields" },
      flow_delete: { restMethod: "tasks.flow.Flow.delete", httpVerb: "POST", pathParams: ["flowId"] },
      flow_isExists: { restMethod: "tasks.flow.Flow.isExists", httpVerb: "GET", pathParams: ["flowId"] },
      flow_activate: { restMethod: "tasks.flow.Flow.activate", httpVerb: "POST", pathParams: ["flowId"] },
      flow_pin: { restMethod: "tasks.flow.Flow.pin", httpVerb: "POST", pathParams: ["flowId"] },
      stage_add: { restMethod: "task.stages.add", httpVerb: "POST", bodyParam: "stageFields", bodyWrapper: "fields" },
      stage_get: { restMethod: "task.stages.get", httpVerb: "GET", pathParams: ["stageId"] },
      stage_update: { restMethod: "task.stages.update", httpVerb: "POST", pathParams: ["stageId"], bodyParam: "stageFields", bodyWrapper: "fields" },
      stage_delete: { restMethod: "task.stages.delete", httpVerb: "POST", pathParams: ["stageId"] },
      stage_canMoveTask: { restMethod: "task.stages.canmovetask", httpVerb: "GET", pathParams: ["taskId", "stageId"] },
      planner_getList: { restMethod: "task.planner.getList", httpVerb: "GET" },
      dependence_add: { restMethod: "task.dependence.add", httpVerb: "POST", pathParams: ["taskId"], bodyParam: "dependsOnId", bodyWrapper: "dependsOnId" },
      dependence_delete: { restMethod: "task.dependence.delete", httpVerb: "POST", pathParams: ["taskId"], bodyParam: "dependsOnId", bodyWrapper: "dependsOnId" },
      userfield_add: { restMethod: "task.item.userfield.add", httpVerb: "POST", bodyParam: "userfield", bodyWrapper: "fields" },
      userfield_update: { restMethod: "task.item.userfield.update", httpVerb: "POST", pathParams: ["userfieldId"], bodyParam: "userfield", bodyWrapper: "fields" },
      userfield_get: { restMethod: "task.item.userfield.get", httpVerb: "GET", pathParams: ["userfieldId"] },
      userfield_list: { restMethod: "task.item.userfield.getlist", httpVerb: "GET" },
      userfield_delete: { restMethod: "task.item.userfield.delete", httpVerb: "POST", pathParams: ["userfieldId"] },
    },
    client,
    {
      add: "Create a task (TITLE required)", update: "Update task fields", get: "Get a task by ID",
      list: "List/filter tasks (my tasks: RESPONSIBLE_ID+STATUS=-1)", delete: "Delete a task (destructive)",
      start: "Start a task", pause: "Pause a task", defer: "Defer a task", complete: "Complete a task", renew: "Renew a completed task",
      delegate: "Delegate a task (userId)", approve: "Approve a task result", disapprove: "Disapprove a task result",
      count: "Count tasks by filter", getFields: "Describe task fields", files_attach: "Attach a file to a task",
      history_list: "List task history", result_add: "Add a task result", result_list: "List task results",
      result_update: "Update a task result", result_delete: "Delete a task result (destructive)",
      addToFlow: "Add a task to a flow", moveToStage: "Move a task to a stage",
      checklist_add: "Add a checklist item", checklist_get: "Get a checklist item", checklist_list: "List checklist items",
      checklist_update: "Update a checklist item", checklist_delete: "Delete a checklist item (destructive)",
      checklist_complete: "Mark a checklist item complete",
      checklist_moveafteritem: "Reorder a checklist item", checklist_renew: "Renew a completed checklist item",
      comment_add: "Add a comment to a task", comment_list: "List task comments",
      comment_update: "Update a comment", comment_delete: "Delete a comment (destructive)",
      elapsed_add: "Add elapsed time to a task", elapsed_update: "Update elapsed time", elapsed_get: "Get an elapsed record",
      elapsed_list: "List elapsed records", elapsed_delete: "Delete an elapsed record (destructive)",
      flow_create: "Create a tasks flow", flow_get: "Get a flow", flow_update: "Update a flow",
      flow_delete: "Delete a flow (destructive)", flow_isExists: "Check if a flow exists",
      flow_activate: "Activate a flow", flow_pin: "Pin a flow",
      stage_add: "Add a kanban stage", stage_get: "Get kanban stages", stage_update: "Update a stage",
      stage_delete: "Delete a stage (destructive)", stage_canMoveTask: "Check if a task can move to a stage",
      planner_getList: "Get daily planner tasks",
      dependence_add: "Add a task dependency (task depends on dependsOnId)",
      dependence_delete: "Remove a task dependency (destructive)",
      userfield_add: "Create a task user field", userfield_update: "Update a task user field",
      userfield_get: "Get a task user field", userfield_list: "List task user fields",
      userfield_delete: "Delete a task user field (destructive)",
    },
  );
}