import type { Bitrix24ApiClient } from "../../api-client.js";
import type { ToolDefinition } from "../../types.js";
import { createActionTool } from "../framework.js";
import { P } from "../params.js";
import { API_VERSION } from "../../constants.js";

export function createMailTool(client: Bitrix24ApiClient): ToolDefinition {
  return createActionTool(
    "bx24_mail",
    `Bitrix24 mail: mailboxes, messages, send, reply, forward, filters, recipient. Methods mail.mailbox.*, mail.message.*, mail.recipient.*, mailservice.* (${API_VERSION}). RU/EN: почта, письмо, отправить письмо, ящик, фильтр / mail, email, send email, mailbox, filter.`,
    ["mailbox_list", "mailbox_get", "mailbox_add", "mailbox_delete", "mailbox_senders", "mailbox_field_list", "mailbox_field_get", "message_list", "message_get", "message_send", "message_delete", "message_reply", "message_forward", "message_mark", "message_movetofolder", "message_createtask", "message_createcalendarevent", "message_createchat", "message_createfeedpost", "message_createcrmactivity", "message_removecrmactivity", "message_field_list", "message_field_get", "recipient_list", "recipient_listcontacts", "recipient_listemployees", "recipient_field_list", "recipient_field_get", "mailservice_list", "mailservice_add", "mailservice_get", "mailservice_delete", "mailservice_fields", "filter_add", "filter_delete", "filter_list"],
    {
      id: P.id, mailboxId: { type: "string", description: "Mailbox ID" },
      messageId: { type: "string", description: "Message ID" },
      fields: { type: "object", description: "Message/mailbox/service fields (per Bitrix24 docs for the method)" },
      filterFields: { type: "object", description: "Filter fields: NAME, MAILBOX_ID, ACTION" },
      folderId: { type: "string", description: "Target folder ID for movetofolder" },
      taskFields: { type: "object", description: "Task fields for message_createtask" },
      filter: P.filter, select: P.select, order: P.order, start: P.start,
    },
    {
      mailbox_list: { restMethod: "mail.mailbox.list", httpVerb: "GET", isList: true },
      mailbox_get: { restMethod: "mail.mailbox.get", httpVerb: "GET", pathParams: ["mailboxId"] },
      mailbox_add: { restMethod: "mail.mailbox.create", httpVerb: "POST", bodyParam: "fields", bodyWrapper: "fields" },
      mailbox_delete: { restMethod: "mail.mailbox.delete", httpVerb: "POST", pathParams: ["mailboxId"] },
      mailbox_senders: { restMethod: "mail.mailbox.senders", httpVerb: "GET", queryParams: ["filter", "select", "order", "start"] },
      mailbox_field_list: { restMethod: "mail.mailbox.field.list", httpVerb: "GET" },
      mailbox_field_get: { restMethod: "mail.mailbox.field.get", httpVerb: "GET" },
      message_list: { restMethod: "mail.message.list", httpVerb: "GET", isList: true, queryParams: ["filter", "select", "order", "start"] },
      message_get: { restMethod: "mail.message.get", httpVerb: "GET", pathParams: ["messageId"] },
      message_send: { restMethod: "mail.message.send", httpVerb: "POST", bodyParam: "fields", bodyWrapper: "fields" },
      message_delete: { restMethod: "mail.message.delete", httpVerb: "POST", pathParams: ["messageId"] },
      message_reply: { restMethod: "mail.message.reply", httpVerb: "POST", pathParams: ["messageId"], bodyParam: "fields", bodyWrapper: "fields" },
      message_forward: { restMethod: "mail.message.forward", httpVerb: "POST", pathParams: ["messageId"], bodyParam: "fields", bodyWrapper: "fields" },
      message_mark: { restMethod: "mail.message.mark", httpVerb: "POST", pathParams: ["messageId"] },
      message_movetofolder: { restMethod: "mail.message.movetofolder", httpVerb: "POST", pathParams: ["messageId"], bodyParam: "folderId", bodyWrapper: "folderId" },
      message_createtask: { restMethod: "mail.message.createtask", httpVerb: "POST", pathParams: ["messageId"], bodyParam: "taskFields", bodyWrapper: "fields" },
      message_createcalendarevent: { restMethod: "mail.message.createcalendarevent", httpVerb: "POST", pathParams: ["messageId"], bodyParam: "fields", bodyWrapper: "fields" },
      message_createchat: { restMethod: "mail.message.createchat", httpVerb: "POST", pathParams: ["messageId"] },
      message_createfeedpost: { restMethod: "mail.message.createfeedpost", httpVerb: "POST", pathParams: ["messageId"], bodyParam: "fields", bodyWrapper: "fields" },
      message_createcrmactivity: { restMethod: "mail.message.createcrmactivity", httpVerb: "POST", pathParams: ["messageId"], bodyParam: "fields", bodyWrapper: "fields" },
      message_removecrmactivity: { restMethod: "mail.message.removecrmactivity", httpVerb: "POST", pathParams: ["messageId"] },
      message_field_list: { restMethod: "mail.message.field.list", httpVerb: "GET" },
      message_field_get: { restMethod: "mail.message.field.get", httpVerb: "GET" },
      recipient_list: { restMethod: "mail.recipient.list", httpVerb: "GET", isList: true, queryParams: ["filter", "select", "order", "start"] },
      recipient_listcontacts: { restMethod: "mail.recipient.listcontacts", httpVerb: "GET", isList: true, queryParams: ["filter", "select", "order", "start"] },
      recipient_listemployees: { restMethod: "mail.recipient.listemployees", httpVerb: "GET", isList: true, queryParams: ["filter", "select", "order", "start"] },
      recipient_field_list: { restMethod: "mail.recipient.field.list", httpVerb: "GET" },
      recipient_field_get: { restMethod: "mail.recipient.field.get", httpVerb: "GET" },
      mailservice_list: { restMethod: "mailservice.list", httpVerb: "GET", isList: true },
      mailservice_add: { restMethod: "mailservice.add", httpVerb: "POST", bodyParam: "fields", bodyWrapper: "fields" },
      mailservice_get: { restMethod: "mailservice.get", httpVerb: "GET", pathParams: ["id"] },
      mailservice_delete: { restMethod: "mailservice.delete", httpVerb: "POST", pathParams: ["id"] },
      mailservice_fields: { restMethod: "mailservice.fields", httpVerb: "GET" },
      filter_add: { restMethod: "mail.filter.add", httpVerb: "POST", bodyParam: "filterFields", bodyWrapper: "fields" },
      filter_delete: { restMethod: "mail.filter.delete", httpVerb: "POST", pathParams: ["id"] },
      filter_list: { restMethod: "mail.filter.list", httpVerb: "GET", isList: true },
    },
    client,
    {
      mailbox_list: "List mailboxes", mailbox_get: "Get a mailbox", mailbox_add: "Add a mailbox", mailbox_delete: "Delete a mailbox (destructive)",
      mailbox_senders: "List available senders for a mailbox", mailbox_field_list: "List mailbox fields", mailbox_field_get: "Get a mailbox field",
      message_list: "List messages", message_get: "Get a message", message_send: "Send an email (TO, SUBJECT, BODY)",
      message_delete: "Delete a message (destructive)", message_reply: "Reply to a message", message_forward: "Forward a message",
      message_mark: "Mark a message (seen/flagged)",
      message_movetofolder: "Move a message to a folder (destructive — leaves inbox)",
      message_createtask: "Create a task from a message", message_createcalendarevent: "Create a calendar event from a message",
      message_createchat: "Create a chat from a message", message_createfeedpost: "Create a news feed post from a message",
      message_createcrmactivity: "Create a CRM activity from a message", message_removecrmactivity: "Remove the CRM activity link from a message (destructive)",
      message_field_list: "List message fields", message_field_get: "Get a message field",
      recipient_list: "List recipients", recipient_listcontacts: "Search address book contacts",
      recipient_listemployees: "Search portal employees", recipient_field_list: "List recipient fields", recipient_field_get: "Get a recipient field",
      mailservice_list: "List mail services", mailservice_add: "Add a mail service", mailservice_get: "Get a mail service",
      mailservice_delete: "Delete a mail service (destructive)", mailservice_fields: "Describe mail service fields",
      filter_add: "Add a mail filter", filter_delete: "Delete a mail filter (destructive)", filter_list: "List mail filters",
    },
  );
}