import type { Bitrix24ApiClient } from "../../api-client.js";
import type { ToolDefinition } from "../../types.js";
import { createActionTool } from "../framework.js";
import { P } from "../params.js";
import { API_VERSION } from "../../constants.js";

export function createTelephonyTool(client: Bitrix24ApiClient): ToolDefinition {
  return createActionTool(
    "bx24_telephony",
    `Bitrix24 telephony: external lines, external calls, SIP, voximplant, call follow-up. Methods telephony.externalLine.*, telephony.externalCall.*, voximplant.*, call.followup.* (${API_VERSION}). RU/EN: телефония, внешняя линия, звонок, SIP, воксимплант, перезвон / telephony, external line, call, sip, follow-up.`,
    ["externalLine_add", "externalLine_delete", "externalLine_list", "externalCall_register", "externalCall_finish", "externalCall_search", "externalCall_show", "externalCall_hide", "externalCall_attachRecord", "externalCall_searchCrmEntities", "call_attachTranscription", "call_followup_get", "voximplant_info", "voximplant_call_search", "voximplant_callback_start", "voximplant_infocall_startwithsound", "voximplant_infocall_startwithtext", "voximplant_tts_voices_get", "voximplant_url_get", "voximplant_statistic_get", "voximplant_line_get", "voximplant_line_outgoing_get", "voximplant_line_outgoing_set", "voximplant_line_outgoing_sip_set", "voximplant_user_get", "voximplant_user_activatePhone", "sip_add", "sip_update", "sip_get", "sip_status", "sip_connector_status", "sip_delete", "sip_list"],
    {
      id: P.id, fields: { type: "object", description: "Line/call/SIP fields (NUMBER, LINE_NUMBER, USER_ID, CALL_ID, ...)" },
      filter: P.filter, select: P.select, order: P.order, start: P.start,
    },
    {
      externalLine_add: { restMethod: "telephony.externalLine.add", httpVerb: "POST", bodyParam: "fields", bodyWrapper: "fields" },
      externalLine_delete: { restMethod: "telephony.externalLine.delete", httpVerb: "POST", pathParams: ["id"] },
      externalLine_list: { restMethod: "telephony.externalLine.list", httpVerb: "GET" },
      externalCall_register: { restMethod: "telephony.externalCall.register", httpVerb: "POST", bodyParam: "fields", bodyWrapper: "fields" },
      externalCall_finish: { restMethod: "telephony.externalCall.finish", httpVerb: "POST", bodyParam: "fields", bodyWrapper: "fields" },
      externalCall_search: { restMethod: "telephony.externalCall.search", httpVerb: "GET", isList: true, queryParams: ["filter", "select", "order", "start"] },
      externalCall_show: { restMethod: "telephony.externalCall.show", httpVerb: "POST", bodyParam: "fields", bodyWrapper: "fields" },
      externalCall_hide: { restMethod: "telephony.externalCall.hide", httpVerb: "POST", bodyParam: "fields", bodyWrapper: "fields" },
      externalCall_attachRecord: { restMethod: "telephony.externalCall.attachRecord", httpVerb: "POST", bodyParam: "fields", bodyWrapper: "fields" },
      externalCall_searchCrmEntities: { restMethod: "telephony.externalCall.searchCrmEntities", httpVerb: "GET", queryParams: ["filter"] },
      call_attachTranscription: { restMethod: "telephony.call.attachTranscription", httpVerb: "POST", bodyParam: "fields", bodyWrapper: "fields" },
      call_followup_get: { restMethod: "call.followup.get", httpVerb: "GET", isList: true, queryParams: ["filter"] },
      voximplant_info: { restMethod: "voximplant.info", httpVerb: "GET" },
      voximplant_call_search: { restMethod: "voximplant.call.search", httpVerb: "GET", isList: true, queryParams: ["filter", "select", "order", "start"] },
      voximplant_callback_start: { restMethod: "voximplant.callback.start", httpVerb: "POST", bodyParam: "fields", bodyWrapper: "fields" },
      voximplant_infocall_startwithsound: { restMethod: "voximplant.infocall.startwithsound", httpVerb: "POST", bodyParam: "fields", bodyWrapper: "fields" },
      voximplant_infocall_startwithtext: { restMethod: "voximplant.infocall.startwithtext", httpVerb: "POST", bodyParam: "fields", bodyWrapper: "fields" },
      voximplant_tts_voices_get: { restMethod: "voximplant.tts.voices.get", httpVerb: "GET" },
      voximplant_url_get: { restMethod: "voximplant.url.get", httpVerb: "GET" },
      voximplant_statistic_get: { restMethod: "voximplant.statistic.get", httpVerb: "GET", isList: true, queryParams: ["filter", "select", "order", "start"] },
      voximplant_line_get: { restMethod: "voximplant.line.get", httpVerb: "GET" },
      voximplant_line_outgoing_get: { restMethod: "voximplant.line.outgoing.get", httpVerb: "GET" },
      voximplant_line_outgoing_set: { restMethod: "voximplant.line.outgoing.set", httpVerb: "POST", bodyParam: "fields", bodyWrapper: "fields" },
      voximplant_line_outgoing_sip_set: { restMethod: "voximplant.line.outgoing.sip.set", httpVerb: "POST", bodyParam: "fields", bodyWrapper: "fields" },
      voximplant_user_get: { restMethod: "voximplant.user.get", httpVerb: "GET", queryParams: ["filter", "select", "order", "start"] },
      voximplant_user_activatePhone: { restMethod: "voximplant.user.activatePhone", httpVerb: "POST", bodyParam: "fields", bodyWrapper: "fields" },
      sip_add: { restMethod: "voximplant.sip.add", httpVerb: "POST", bodyParam: "fields", bodyWrapper: "fields" },
      sip_update: { restMethod: "voximplant.sip.update", httpVerb: "POST", pathParams: ["id"], bodyParam: "fields", bodyWrapper: "fields" },
      sip_get: { restMethod: "voximplant.sip.get", httpVerb: "GET" },
      sip_status: { restMethod: "voximplant.sip.status", httpVerb: "GET", pathParams: ["id"] },
      sip_connector_status: { restMethod: "voximplant.sip.connector.status", httpVerb: "GET" },
      sip_delete: { restMethod: "voximplant.sip.delete", httpVerb: "POST", pathParams: ["id"] },
      sip_list: { restMethod: "voximplant.sip.list", httpVerb: "GET" },
    },
    client,
    {
      externalLine_add: "Add an external line", externalLine_delete: "Delete an external line (destructive)", externalLine_list: "List external lines",
      externalCall_register: "Register an external call", externalCall_finish: "Finish an external call",
      externalCall_search: "Search external call history",
      externalCall_show: "Show the call card to a user", externalCall_hide: "Hide the call card",
      externalCall_attachRecord: "Attach a call recording to a call",
      externalCall_searchCrmEntities: "Search CRM entities by phone number",
      call_attachTranscription: "Attach a call transcription to a call",
      call_followup_get: "Get call follow-ups",
      voximplant_info: "Get VoxImplant account info", voximplant_call_search: "Search VoxImplant calls",
      voximplant_callback_start: "Start a callback to a user", voximplant_infocall_startwithsound: "Auto-call a number playing an MP3",
      voximplant_infocall_startwithtext: "Auto-call a number with TTS text",
      voximplant_tts_voices_get: "List available TTS voices", voximplant_url_get: "Get telephony URLs",
      voximplant_statistic_get: "Get call statistics", voximplant_line_get: "List outbound lines",
      voximplant_line_outgoing_get: "Get the default outbound line", voximplant_line_outgoing_set: "Set the default outbound line",
      voximplant_line_outgoing_sip_set: "Set the default SIP outbound line",
      voximplant_user_get: "Get user telephony settings", voximplant_user_activatePhone: "Activate a user's SIP phone",
      sip_add: "Add a SIP line", sip_update: "Update a SIP line", sip_get: "List SIP connections",
      sip_status: "Get SIP registration status", sip_connector_status: "Get SIP connector status",
      sip_delete: "Delete a SIP line (destructive)", sip_list: "List SIP lines",
    },
  );
}